version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: magiclog-car-factory
    container_name: magiclog-app
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      APP_NAME: "MagicLog Car Factory"
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      APP_LOCALE: ${APP_LOCALE}
      APP_FALLBACK_LOCALE: ${APP_FALLBACK_LOCALE}
      APP_FAKER_LOCALE: ${APP_FAKER_LOCALE}
      APP_MAINTENANCE_DRIVER: ${APP_MAINTENANCE_DRIVER}
      PHP_CLI_SERVER_WORKERS: ${PHP_CLI_SERVER_WORKERS}
      PHP_ALLOW_URL_FOPEN: ${PHP_ALLOW_URL_FOPEN}
      BCRYPT_ROUNDS: ${BCRYPT_ROUNDS}
      LOG_CHANNEL: ${LOG_CHANNEL}
      LOG_STACK: ${LOG_STACK}
      LOG_DEPRECATIONS_CHANNEL: ${LOG_DEPRECATIONS_CHANNEL}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SESSION_DRIVER: ${SESSION_DRIVER}
      SESSION_LIFETIME: ${SESSION_LIFETIME}
      SESSION_ENCRYPT: ${SESSION_ENCRYPT}
      SESSION_PATH: ${SESSION_PATH}
      SESSION_DOMAIN: ${SESSION_DOMAIN}
      BROADCAST_CONNECTION: ${BROADCAST_CONNECTION}
      FILESYSTEM_DISK: ${FILESYSTEM_DISK}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION}
      CACHE_STORE: ${CACHE_STORE}
      MEMCACHED_HOST: ${MEMCACHED_HOST}
      REDIS_CLIENT: ${REDIS_CLIENT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_SCHEME: ${MAIL_SCHEME}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_USE_PATH_STYLE_ENDPOINT: ${AWS_USE_PATH_STYLE_ENDPOINT}
      VITE_APP_NAME: ${VITE_APP_NAME}
    command: 
      sh -c "php artisan migrate --force && php-fpm"
    volumes:
      - ./:/var/www
      - magiclog-storage:/var/www/storage
      - magiclog-cache:/var/www/bootstrap/cache
    networks:
      - magiclog

  db:
    image: mysql:8.0
    container_name: magiclog-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - magiclog-data:/var/lib/mysql
    networks:
      - magiclog

  nginx:
    image: nginx:alpine
    container_name: magiclog-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
      - magiclog-storage:/var/www/storage
      - magiclog-cache:/var/www/bootstrap/cache
    networks:
      - magiclog

  redis:
    image: redis:alpine
    container_name: magiclog-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - magiclog

networks:
  magiclog:
    driver: bridge

volumes:
  magiclog-data:
    driver: local
  magiclog-storage:
    driver: local
  magiclog-cache:
    driver: local
